version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Asegúrate de que este Dockerfile esté en el mismo directorio
    ports:
      - "3000:3000"           # Mapea el puerto 3000 del contenedor al host
    environment:
      - DB_HOST=db            # Nombre del servicio de la base de datos
      - DB_USER=root          # Usuario de la base de datos
      - DB_PASSWORD=12345  # Contraseña de la base de datos
      - DB_NAME=supermercado          # Nombre de la base de datos
    depends_on:
      - db                    # Asegura que el contenedor de la base de datos se inicie primero

  db:
    image: mysql:latest      # Imagen de MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345  # Contraseña del usuario root
      MYSQL_DATABASE: supermercado            # Base de datos que se crea al iniciar
    ports:
      - "3307:3306"          # Mapea el puerto 3306 del contenedor al host
